Cross compile fixes and minor updates to tests.
Fix undefined reference to `rpl_malloc'
Add build notes for Trinitite-like systems.
Update demo does to not have include guards.